controllers:
    resource: '../src/Controller/'
    type: attribute

ticket_page:
    path: /ticket
    controller: App\Controller\TicketController::ticket
dash:
    path: /dashboard
    controller: App\Controller\DashboardController::index

index:
    path: /
    controller: App\Controller\HomeController::index
signin:
    path: /signin
    controller: App\Controller\SigninController::signin
signup:
    path: /signup
    controller: App\Controller\SignupController::signup
app_user_index:
    path: /user
    controller: App\Controller\UserController::index

app_user_new:
    path: /user/new
    controller: App\Controller\UserController::new

app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show

app_user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit



tables:
    path: /tables
    controller: App\Controller\DashController::tables


api_formations:
    path: /api/formations
    controller: App\Controller\FormationController::getFormations
    methods: GET    
api_evenements:
  path: /api/evenements
  controller: App\Controller\ApiEvenementController::getEvenements